version: '3.8'

services:
  roundcube-db:
    image: postgres:15-alpine
    container_name: roundcube-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: roundcube
      POSTGRES_USER: roundcube
      POSTGRES_PASSWORD: ${ROUNDCUBE_DB_PASSWORD}
    volumes:
      - roundcube-db-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roundcube"]
      interval: 10s
      timeout: 5s
      retries: 5

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    depends_on:
      roundcube-db:
        condition: service_healthy
    environment:
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: roundcube-db
      ROUNDCUBEMAIL_DB_PORT: 5432
      ROUNDCUBEMAIL_DB_USER: roundcube
      ROUNDCUBEMAIL_DB_PASSWORD: ${ROUNDCUBE_DB_PASSWORD}
      ROUNDCUBEMAIL_DB_NAME: roundcube
      ROUNDCUBEMAIL_DEFAULT_HOST: ${IMAP_HOST}
      ROUNDCUBEMAIL_DEFAULT_PORT: ${IMAP_PORT}
      ROUNDCUBEMAIL_SMTP_SERVER: ${SMTP_HOST}
      ROUNDCUBEMAIL_SMTP_PORT: ${SMTP_PORT}
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 25M
      ROUNDCUBEMAIL_SKIN: elastic
    volumes:
      - roundcube-data:/var/www/html
      - ./config/roundcube/config.inc.php:/var/www/html/config/config.inc.php:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"

      # HTTP Router (redirect to HTTPS)
      - "traefik.http.routers.roundcube-http.rule=Host(`${MAIL_DOMAIN}`)"
      - "traefik.http.routers.roundcube-http.entrypoints=web"
      - "traefik.http.routers.roundcube-http.middlewares=redirect-to-https@file"

      # HTTPS Router
      - "traefik.http.routers.roundcube-https.rule=Host(`${MAIL_DOMAIN}`)"
      - "traefik.http.routers.roundcube-https.entrypoints=websecure"
      - "traefik.http.routers.roundcube-https.tls=true"
      - "traefik.http.routers.roundcube-https.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"

      # Service
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  roundcube-db-data:
    name: roundcube-db-data
  roundcube-data:
    name: roundcube-data

networks:
  email-network:
    name: email-network
    driver: bridge
  traefik-network:
    name: traefik-network
    external: true
