version: '3.8'

services:
  # PostgreSQL Database
  mail-db:
    image: postgres:15-alpine
    container_name: mail-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mailserver
      POSTGRES_USER: mailuser
      POSTGRES_PASSWORD: ${MAIL_DB_PASSWORD}
    volumes:
      - mail-db-data:/var/lib/postgresql/data
      - ./config/postfix/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Roundcube Database
  roundcube-db:
    image: postgres:15-alpine
    container_name: roundcube-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: roundcube
      POSTGRES_USER: roundcube
      POSTGRES_PASSWORD: ${ROUNDCUBE_DB_PASSWORD}
    volumes:
      - roundcube-db-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roundcube"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Postfix (SMTP Server)
  postfix:
    image: boky/postfix:latest
    container_name: postfix
    restart: unless-stopped
    depends_on:
      mail-db:
        condition: service_healthy
    environment:
      HOSTNAME: ${MAIL_HOSTNAME}
      ALLOWED_SENDER_DOMAINS: ${MAIL_DOMAIN}
      RELAYHOST: ${RELAYHOST:-}
      RELAYHOST_USERNAME: ${RELAYHOST_USERNAME:-}
      RELAYHOST_PASSWORD: ${RELAYHOST_PASSWORD:-}
      MESSAGE_SIZE_LIMIT: 26214400
    volumes:
      - postfix-data:/var/spool/postfix
      - postfix-queue:/var/mail
      - ./config/postfix/main.cf:/etc/postfix/main.cf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
      - traefik-network
    ports:
      - "25:25"   # SMTP
      - "587:587" # SMTP Submission
    labels:
      - "traefik.enable=false"

  # Dovecot (IMAP/POP3 Server)
  dovecot:
    image: dovecot/dovecot:latest
    container_name: dovecot
    restart: unless-stopped
    depends_on:
      mail-db:
        condition: service_healthy
    environment:
      HOSTNAME: ${MAIL_HOSTNAME}
      DOMAIN: ${MAIL_DOMAIN}
    volumes:
      - dovecot-data:/var/mail
      - dovecot-config:/etc/dovecot
      - ./config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf:ro
      - ./config/dovecot/conf.d:/etc/dovecot/conf.d:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
    ports:
      - "143:143"  # IMAP
      - "993:993"  # IMAPS
      - "110:110"  # POP3
      - "995:995"  # POP3S

  # Rspamd (Anti-spam filter)
  rspamd:
    image: a-mail/rspamd:latest
    container_name: rspamd
    restart: unless-stopped
    environment:
      DOMAIN: ${MAIL_DOMAIN}
    volumes:
      - rspamd-data:/var/lib/rspamd
      - ./config/rspamd:/etc/rspamd/override.d:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"

      # HTTP Router (redirect to HTTPS)
      - "traefik.http.routers.rspamd-http.rule=Host(`rspamd.${MAIL_DOMAIN}`)"
      - "traefik.http.routers.rspamd-http.entrypoints=web"
      - "traefik.http.routers.rspamd-http.middlewares=redirect-to-https@file"

      # HTTPS Router
      - "traefik.http.routers.rspamd-https.rule=Host(`rspamd.${MAIL_DOMAIN}`)"
      - "traefik.http.routers.rspamd-https.entrypoints=websecure"
      - "traefik.http.routers.rspamd-https.tls=true"
      - "traefik.http.routers.rspamd-https.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"

      # Service
      - "traefik.http.services.rspamd.loadbalancer.server.port=11334"

  # Roundcube (Webmail)
  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    depends_on:
      roundcube-db:
        condition: service_healthy
      dovecot:
        condition: service_started
      postfix:
        condition: service_started
    environment:
      ROUNDCUBEMAIL_DB_TYPE: pgsql
      ROUNDCUBEMAIL_DB_HOST: roundcube-db
      ROUNDCUBEMAIL_DB_PORT: 5432
      ROUNDCUBEMAIL_DB_USER: roundcube
      ROUNDCUBEMAIL_DB_PASSWORD: ${ROUNDCUBE_DB_PASSWORD}
      ROUNDCUBEMAIL_DB_NAME: roundcube
      ROUNDCUBEMAIL_DEFAULT_HOST: ssl://dovecot
      ROUNDCUBEMAIL_DEFAULT_PORT: 993
      ROUNDCUBEMAIL_SMTP_SERVER: tls://postfix
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 25M
      ROUNDCUBEMAIL_SKIN: elastic
    volumes:
      - roundcube-data:/var/www/html
      - ./config/roundcube/config.inc.php:/var/www/html/config/config.inc.php:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - email-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-network"

      # HTTP Router (redirect to HTTPS)
      - "traefik.http.routers.roundcube-http.rule=Host(`mail.${MAIL_DOMAIN}`)"
      - "traefik.http.routers.roundcube-http.entrypoints=web"
      - "traefik.http.routers.roundcube-http.middlewares=redirect-to-https@file"

      # HTTPS Router
      - "traefik.http.routers.roundcube-https.rule=Host(`mail.${MAIL_DOMAIN}`)"
      - "traefik.http.routers.roundcube-https.entrypoints=websecure"
      - "traefik.http.routers.roundcube-https.tls=true"
      - "traefik.http.routers.roundcube-https.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"

      # Service
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mail-db-data:
    name: mail-db-data
  roundcube-db-data:
    name: roundcube-db-data
  postfix-data:
    name: postfix-data
  postfix-queue:
    name: postfix-queue
  dovecot-data:
    name: dovecot-data
  dovecot-config:
    name: dovecot-config
  rspamd-data:
    name: rspamd-data
  roundcube-data:
    name: roundcube-data

networks:
  email-network:
    name: email-network
    driver: bridge
  traefik-network:
    name: traefik-network
    external: true
